Dev/stam/matomo
arup-group/SpeckleCore pull request #5
Opened 2021-04-12 15:30 UTC by psarras

- Added Matomo classes to track Events for Stream Send, Stream Receive.
- Placeholders for custom dimensions.

2021-04-12 19:04 UTC, peterjgrainger requested changes

2021-04-12 19:04 UTC, peterjgrainger commented on SpeckleCore/MatomoTelemetry.cs
> +            //piwikTracker.DoTrackPageView("Record Metadata");
You don't want to track the page view, maybe remove this?
```suggestion
```

2021-04-13 10:03 UTC, psarras commented on SpeckleCore/MatomoTelemetry.cs
> +            //piwikTracker.DoTrackPageView("Record Metadata");
Well, this goes side by side with my confusion regarding how we track Custom Dimensions. On the examples they use this line to track those. But it is not clear to me if I can supersede it with the DoTrackEvent alternative or these are two different things I need to track... Regardless I was just trying different alternatives. Let me know if you understood anything, otherwise I will put a not above this line for future reference.

2021-04-13 12:50 UTC, peterjgrainger approved these changes

2021-04-13 12:50 UTC, peterjgrainger commented on SpeckleCore/MatomoTelemetry.cs
> +            //piwikTracker.DoTrackPageView("Record Metadata");
I thought it was a mistake :)

I don't normally leave in commented code as I've seen my fair share of commented code that was never removed. It always makes me uneasy :)

2021-04-13 13:58 UTC, psarras commented on SpeckleCore/MatomoTelemetry.cs
> +            //piwikTracker.DoTrackPageView("Record Metadata");
Totally with you on this one, I hate leaving commented code as well...Unfortunately this is unfinished work... :(

2021-04-13 13:58 UTC, merged